[package]
name = "tpath"
version = "0.1.0"
authors = ["amirpouya@nyu.edu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
rayon = "*"
hashbrown = { version = "0.12.0", features = ["rayon"] }
